# Generated by Django 4.2.7 on 2025-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='supabase_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
