# Generated by Django 4.2.7 on 2025-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_supabase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Under Review')], default='pending', max_length=20),
        ),
    ]
