# Generated by Django 4.2.7 on 2025-02-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_add_status_field'),
        ('analysis', '0003_analysis_status'),
    ]

    operations = [
    ]
